/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int TIPO = 9;
  /** RegularExpression Id. */
  int NEWVAR = 10;
  /** RegularExpression Id. */
  int PV = 11;
  /** RegularExpression Id. */
  int SYSTEMOUTPUT = 12;
  /** RegularExpression Id. */
  int OPENPAR = 13;
  /** RegularExpression Id. */
  int CLOSEPAR = 14;
  /** RegularExpression Id. */
  int RETURN = 15;
  /** RegularExpression Id. */
  int REPEAT = 16;
  /** RegularExpression Id. */
  int UNTIL = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int THEN = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int FUNC = 23;
  /** RegularExpression Id. */
  int FACAO_OPCIONAL = 24;
  /** RegularExpression Id. */
  int EXP_OPCIONAL = 25;
  /** RegularExpression Id. */
  int CHAR = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int OP = 28;
  /** RegularExpression Id. */
  int ID = 29;
  /** RegularExpression Id. */
  int NUM = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "<TIPO>",
    "\"newVar\"",
    "\";\"",
    "\"System.output\"",
    "\"(\"",
    "\")\"",
    "\"return\"",
    "\"repeat\"",
    "\"until\"",
    "\"while\"",
    "\"if\"",
    "\"then\"",
    "\"true\"",
    "\"false\"",
    "\"func\"",
    "<FACAO_OPCIONAL>",
    "<EXP_OPCIONAL>",
    "<CHAR>",
    "<DIGIT>",
    "<OP>",
    "<ID>",
    "<NUM>",
    "\",\"",
    "\"=\"",
  };

}
