/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int TIPO = 9;
  /** RegularExpression Id. */
  int NEWVAR = 10;
  /** RegularExpression Id. */
  int PV = 11;
  /** RegularExpression Id. */
  int FACAO_OPCIONAL = 12;
  /** RegularExpression Id. */
  int EXP_OPCIONAL = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int DIGIT = 15;
  /** RegularExpression Id. */
  int ID = 16;
  /** RegularExpression Id. */
  int NUM = 17;
  /** RegularExpression Id. */
  int VARDECL = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "<TIPO>",
    "\"newVar\"",
    "\";\"",
    "<FACAO_OPCIONAL>",
    "<EXP_OPCIONAL>",
    "<CHAR>",
    "<DIGIT>",
    "<ID>",
    "<NUM>",
    "<VARDECL>",
  };

}
